
services:
  mongo:
    image: mongo:6.0
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_DATABASE: library
    ports:
      - "27017:27017"
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  app:
    build: .
    image: welkinoid/akash:01
    container_name: front-end-container
    restart: always
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB_NAME: library
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 5000
    depends_on:
      - mongo
      - redis
    ports:
      - "5000:5000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
